[package]
authors = ["Zoran Zaric <zz@zoranzaric.de>"]
name = "emnify_filter"
version = "0.1.0"

[dependencies]
futures = "0.1.14"
hyper = "0.11.6"
serde = "1.0.19"
serde_derive = "1.0.19"
serde_json = "1.0"
